### PR TITLE
fixed accordion overflow

### PR DESCRIPTION
**Pull request by Tedfulk**

### CODE REVIEW

**Comment by Tedfulk** [comment]
Screenshot 2024-08-01 at 11 46 55 AM

**Comment by Tedfulk** [comment]
Can also keep the height at 24rem and implement the scroll with no scrollbar if you want. Just thought you'd want to keep it consistent like the accordions below.

**Comment by jph00** [comment]
Many thanks for this PR! I think keeping the height fixed would be even better, if that's OK?

**Comment by jph00** [comment]
@Tedfulk just bumping this if that's ok

**Comment by Tedfulk** [comment]
@jph00 sorry been on vacation, should be able to get it on Mon or Tuesday

**Comment by jph00** [comment]
No problem - just checking in since some other folks were asking about it (I think because they're keen to help!)

Hope you had a great trip :D

**Comment by Tedfulk** [comment]
Is this what you were thinking?

Screenshot 2024-08-11 at 7 15 30 AM
Screenshot 2024-08-11 at 7 15 08 AM
Screenshot 2024-08-11 at 7 15 16 AM

**Comment by Tedfulk** [comment]
@jph00 is this what you were thinking?

Screenshot 2024-08-11 at 7 51 00 AM
Screenshot 2024-08-11 at 7 51 15 AM
Screenshot 2024-08-11 at 7 51 23 AM

**Comment by Tedfulk** [comment]
I also kept on getting an error for a key in the weather.py. Don't know if the api call changed the structure of their data but I added a fix for it too but can take that out if you want.

**Comment by jph00** [comment]
Yes exactly! Thanks for checking :D

**Comment by Tedfulk** [comment]
I had a weird time with the tailwind not applying the style but the only way I could get it to apply the overflow-y-auto was with a style tag.

**Comment by jph00** [comment]
Oh right - to use new classes you have to save the index.html locally and
then run the tailwind cli (with --minify) to generate a new css file, and
replace the existing one.

**Comment by Tedfulk** [comment]
@jph00 Sorry, I'm not sure I follow. How do I generate the index.html locally? 

The only the dep I have is python-fasthtml. Do I have to npm install tailwind and go through the typical installation steps?

**Comment by Tedfulk** [comment]
@jph00 Would you be able to point me to a reference? I've skimmed through a various of your documentation, examples, and hour video. I'm just unsure where to look.

**Comment by jph00** [comment]
Oh it's nothing fancy @Tedfulk  -- you literally just open the local site in your browser, and then click File->Save! :D 

(Yes we do need a better way to handle this... ;) )

**Comment by Tedfulk** [comment]
@jph00 cool thanks for the help, I figured it out. 
step 1: make the tailwind changes in main.py
step 2: run server
step 3: File->save as index.html in root dir 
step 4: npx tailwindcss -o css/tailwind.css --minify
step 5: run server and check to see if changes were correct

**Comment by jph00** [comment]
Thank you ! :D

**Pull request merged**
